### ISSUE TITLE
Not usable due to a casing error

### ISSUE THREAD

**Issue by janbrogger** [ogroppo/fluent-neo4j#4]
The code spells "booleanOPerators" sometimes, which leads the code to fail when used. 

REPRO:
1. On the command line, enter "`npm install fluent-neo4j`"
2. On the command line, enter "`node --require fluent-neo4j`"
OBSERVED:

> internal/modules/cjs/loader.js:1023
>   throw err;
>   ^
> 
> Error: Cannot find module './constants/booleanOPerators'
> Require stack:
> - /home/ogroppo/node_modules/fluent-cypher/CypherQuery.js
> - /home/ogroppo/node_modules/fluent-cypher/index.js
> - /home/ogroppo/node_modules/fluent-neo4j/Neo4jQuery.js
> - /home/ogroppo/node_modules/fluent-neo4j/index.js
> - internal/preload
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:890:27)
>     at Module.require (internal/modules/cjs/loader.js:1080:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/home/ogroppo/node_modules/fluent-cypher/CypherQuery.js:17:26)
>     at Module._compile (internal/modules/cjs/loader.js:1176:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
>     at Module.load (internal/modules/cjs/loader.js:1040:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:929:14)
>     at Module.require (internal/modules/cjs/loader.js:1080:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/ogroppo/node_modules/fluent-cypher/CypherQuery.js',
>     '/home/ogroppo/node_modules/fluent-cypher/index.js',
>     '/home/ogroppo/node_modules/fluent-neo4j/Neo4jQuery.js',
>     '/home/ogroppo/node_modules/fluent-neo4j/index.js',
>     'internal/preload'
>   ]
> }
> 
EXPECTED
No error.

**Comment by ogroppo** [comment]
Hi Jan!
Thank you for your interest in this package. 

The typo has been fixed in version fluent-neo4j@0.4.7 please let me know if this works for you and what OS are you using.

On a separate note, if you're working on projects of scientific interest, feel free to share!
